services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
