POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "andy",
    "url": "testUrl",
    "title": "testTitle"
}
###
http://localhost:3001/api/blogs
###
http://localhost:3001/api/blogs/2
###
DELETE http://localhost:3001/api/blogs/6
###
PUT http://localhost:3001/api/blogs/7
Content-Type: application/json

{
    "likes": 4
}