POST http://localhost:3001/api/blogs
Content-Type: application/json
    Authorization: bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpQGpva3UuZmkiLCJpZCI6MSwiaWF0IjoxNzM0MTg1MzE5fQ.hkFJe4BqIh0u-1LWsTeexLoHsCYAuwtL905p5RzDeLA

{
    "author": "mluukkai",
    "url": "test.com",
    "title": "test title",
    "year": 1992
}
###
http://localhost:3001/api/blogs
###
http://localhost:3001/api/blogs?search=psql
###
http://localhost:3001/api/blogs/2
###
DELETE http://localhost:3001/api/blogs/10
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpQGpva3UuZmkiLCJpZCI6MywiaWF0IjoxNzMzOTQ4Mjc2fQ.xR5JaeLpg95uIqKm9ZnrtUrjbV0GSX1hBbOQUFucERU

###
PUT http://localhost:3001/api/blogs/11
Content-Type: application/json

{
    "likes": 10
}