POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpQGpva3UuZmkiLCJpZCI6MywiaWF0IjoxNzMzOTQ4Mjc2fQ.xR5JaeLpg95uIqKm9ZnrtUrjbV0GSX1hBbOQUFucERU

{
    "author": "mluukkai",
    "url": "fullstackopen.com",
    "title": "Full Stack open"
}
###
http://localhost:3001/api/blogs
###
http://localhost:3001/api/blogs?search=psql
###
http://localhost:3001/api/blogs/2
###
DELETE http://localhost:3001/api/blogs/10
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpQGpva3UuZmkiLCJpZCI6MywiaWF0IjoxNzMzOTQ4Mjc2fQ.xR5JaeLpg95uIqKm9ZnrtUrjbV0GSX1hBbOQUFucERU

###
PUT http://localhost:3001/api/blogs/7
Content-Type: application/json

{
    "likes": 1
}