POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
    "blogId": 3,
    "userId": 1
}

PUT http://localhost:3001/api/readinglists
Content-Type: application/json

{
    "read": true
}