http://localhost:3001/api/users
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "mluukkai@joku.fi",
    "name": "Matti Luukkainen",
    "password": "secret"
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "olsandy",
    "name": "Andy Olsson",
    "password": "passu"
}
###
PUT http://localhost:3001/api/users/2
Content-Type: application/json

{
    "username": "olsand"
}